apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tasman
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: tasman
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 85
