apiVersion: v1
kind: Service
metadata:
  name: tasman                          # name of your Service
spec:                                   # defines what is in this resource
  type: NodePort
  ports:
  - port: 80                            # Make you rervice object available on this port
    targetPort: 4567                    # The targeted-pods have exposed this port
    # nodePort: 30001                   # K8s will automatically map to a port 30000-32767
    # protocol: TCP                     # TCP by default
  selector:
    app: tasman

  # From K8s documentation:
  # If there are external IPs that route to one or more cluster nodes,
  # Kubernetes services can be exposed on those externalIPs.
  # Traffic that ingresses into the cluster with the external IP (as destination IP),
  # on the service port, will be routed to one of the service endpoints.

  # externalIPs:
  #   - 192.168.99.100                    # my minikube-ip
